apiVersion: v1
kind: Service
metadata:
  name: default-http-backend-service
  labels:
    app: default-http-backend-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: default-http-backend-deployment
