apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: foo.com
    http:
      paths:
      - backend:
          serviceName: microbot-service
          servicePort: 80
