---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Project }}-jenkins
  labels:
    app: {{ .Values.Project }}-jenkins
    component: "{{ .Values.Project }}-jenkins-master"
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    component: "{{ .Values.Project }}-jenkins-master"
  type: NodePort
