---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Release.Name }}.k8s1.bobclarke.info.
  name: {{ .Release.Name }}-jenkins
  labels:
    app: {{ .Release.Name }}-jenkins
    component: "{{ .Release.Name }}-jenkins-master"
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    component: "{{ .Release.Name }}-jenkins-master"
  type: LoadBalancer
