---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    app: {{ .Release.Name }}-jenkins
type: Opaque
data:
  jenkins-admin-password: "YWRtaW4="
  jenkins-admin-user: "YWRtaW4="
  
