---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    #k8s-app: nginx-ingress-lb
    app: nginx-ingress-controller-deployment
