apiVersion: v1
kind: Service
metadata:
  labels:
    run: microbot
  name: microbot-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: microbot
status:
  loadBalancer: {}
