apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: load-balancer-example
  name: hello-world-cip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: load-balancer-example
status:
  loadBalancer: {}
