apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    run: load-balancer-example
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: load-balancer-example
