apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress-rules
spec:
  rules:
  - host: minikube
    http:
      paths: 
      - path: /jenkins
        backend:
          serviceName: hello-world-cip
          servicePort: 8080
