---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.Project }}-jenkins
  labels:
    component: "{{ .Values.Project }}-jenkins-master"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Values.Project }}-jenkins-master"
  template:
    metadata:
      labels:
        app: {{ .Values.Project }}-jenkins
        component: "{{ .Values.Project }}-jenkins-master"
      annotations:
        checksum/config: 91496c3e313e4a17590717b4a10615a0c10f90250e6e40ab23ffc92d88fc3b8a
    spec:
      securityContext:
        runAsUser: 0
      serviceAccountName: "default"

      initContainers:
        - name: "copy-default-config"
          image: "jenkins/jenkins:lts"
          imagePullPolicy: "Always"
          command: [ "sh", "/var/jenkins_config/apply_config.sh" ]
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: /var/jenkins_config
              name: jenkins-config
            - mountPath: /usr/share/jenkins/ref/plugins/
              name: plugin-dir
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir

      containers:
        - name: {{ .Values.Project }}-jenkins
          image: "jenkins/jenkins:lts"
          imagePullPolicy: "Always"
          args: [ "--argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)",  "--argumentsRealm.roles.$(ADMIN_USER)=admin"]
          env:
            - name: JAVA_OPTS
              value: ""
            - name: JENKINS_OPTS
              value: ""
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Project }}-jenkins
                  key: jenkins-admin-password
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Project }}-jenkins
                  key: jenkins-admin-user
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: slavelistener
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 60
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
              readOnly: false
            - mountPath: /var/jenkins_config
              name: jenkins-config
              readOnly: true
            - mountPath: /usr/share/jenkins/ref/plugins/
              name: plugin-dir
              readOnly: false
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir
              readOnly: false
      volumes:
      - name: jenkins-config
        configMap:
          name: {{ .Values.Project }}-jenkins-config

      - name: jenkins-home
        hostPath:
          path: /Users/bclar6/kubernetes/volumes/{{ .Values.Project }}-jenkins/home

      - name: plugin-dir
        emptyDir: {}

      - name: secrets-dir
        emptyDir: {}
