kind: Service
apiVersion: v1
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: green.k8s1.bobclarke.info.
  name: nginx-green
spec:
  selector:
    app: nginx-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
