apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    app: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
      - name: nginx-green
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-green-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-green-content
        configMap:
          name: nginx-green

